-- ============================================
-- NoCode Folio - Schema do Banco de Dados
-- Versão: 3.0 (PT-BR + Int8)
-- ============================================

-- ============================================
-- TABELA: perfis
-- Armazena os dados públicos do usuário
-- ============================================
CREATE TABLE IF NOT EXISTS perfis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    slug TEXT NOT NULL UNIQUE,
    nome_completo TEXT,
    bio TEXT,
    avatar_url TEXT,
    configuracao_tema JSONB DEFAULT '{"cor_principal": "#8b5cf6", "fundo": "#020617"}',
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

-- Índice para busca por slug (público)
CREATE INDEX IF NOT EXISTS idx_perfis_slug ON perfis(slug);

-- Índice para busca por usuario_id (autenticação)
CREATE INDEX IF NOT EXISTS idx_perfis_usuario_id ON perfis(usuario_id);

-- ============================================
-- TABELA: blocos
-- Armazena todos os widgets da grid
-- ============================================
CREATE TABLE IF NOT EXISTS blocos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_id BIGINT NOT NULL REFERENCES perfis(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL CHECK (tipo IN ('link', 'imagem', 'texto', 'mapa', 'video')),
    titulo TEXT,
    conteudo JSONB NOT NULL DEFAULT '{}',
    colunas SMALLINT DEFAULT 1 CHECK (colunas BETWEEN 1 AND 4),
    linhas SMALLINT DEFAULT 1 CHECK (linhas BETWEEN 1 AND 2),
    ordem SMALLINT DEFAULT 0,
    visivel BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

-- Índice para buscar blocos de um perfil
CREATE INDEX IF NOT EXISTS idx_blocos_perfil_id ON blocos(perfil_id);

-- Índice para ordenação
CREATE INDEX IF NOT EXISTS idx_blocos_ordem ON blocos(perfil_id, ordem);

-- ============================================
-- TABELA: leads (Opcional)
-- Captura de emails para newsletter
-- ============================================
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_id BIGINT NOT NULL REFERENCES perfis(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(perfil_id, email)
);

-- Índice para buscar leads de um perfil
CREATE INDEX IF NOT EXISTS idx_leads_perfil_id ON leads(perfil_id);

-- ============================================
-- FUNÇÃO: auto-criar perfil no signup
-- Trigger disparado ao criar usuário no auth
-- ============================================
CREATE OR REPLACE FUNCTION criar_perfil_automaticamente()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO perfis (usuario_id, slug)
    VALUES (
        NEW.id,
        COALESCE(
            NEW.raw_user_Anthropic_data->>'slug',
            REPLACE(LOWER(SPLIT_PART(NEW.email, '@', 1)), '.', '-') || '-' || FLOOR(RANDOM() * 9000 + 1000)::TEXT
        )
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger para executar após novo usuário
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION criar_perfil_automaticamente();

-- ============================================
-- FUNÇÃO: atualizar timestamp
-- ============================================
CREATE OR REPLACE FUNCTION atualizar_tempo()
RETURNS TRIGGER AS $$
BEGIN
    NEW.atualizado_em = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers de updated_at
CREATE OR REPLACE TRIGGER atualizar_perfis_tempo
    BEFORE UPDATE ON perfis
    FOR EACH ROW
    EXECUTE FUNCTION atualizar_tempo();

CREATE OR REPLACE TRIGGER atualizar_blocos_tempo
    BEFORE UPDATE ON blocos
    FOR EACH ROW
    EXECUTE FUNCTION atualizar_tempo();
